services:
  api:
    container_name: api_container
    pull_policy: if_not_present
    build:
      context: .
      dockerfile: apps/api/Dockerfile.prod
      args:
        - NODE_ENV=production
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    environment:
      MSSQL_HOST: ${MSSQL_HOST}
      MSSQL_PORT: ${MSSQL_PORT}
      MSSQL_USERNAME: ${MSSQL_USERNAME}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_DB: ${MSSQL_DB}
      DATABASE_URL: sqlserver://${MSSQL_HOST}:${MSSQL_PORT};database=${MSSQL_DB};user=${MSSQL_USERNAME};password=${MSSQL_PASSWORD};trustServerCertificate=true
      API_PORT: ${API_PORT}
    restart: always
    networks:
      - general
  app:
    container_name: app_container
    build:
      context: .
      dockerfile: apps/web/Dockerfile.prod
      args:
        - NODE_ENV=production
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    depends_on:
      - api
    restart: always
    networks:
      - general
  nginx:
    container_name: nginx_container
    build:
      context: .
      dockerfile: packages/gateway/Dockerfile.prod
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    restart: always
    ports:
      - '80:80'
    networks:
      - general
    depends_on:
      - app
      - api
networks:
  general:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
